<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Login" targetNamespace="http://server.webservices.dgac.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://server.webservices.dgac.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://server.webservices.dgac.org/" schemaLocation="Login_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="loginResponse">
    <wsdl:part name="parameters" element="tns:loginResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="login">
    <wsdl:part name="parameters" element="tns:login">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Login">
    <wsdl:operation name="login">
      <wsdl:input name="login" message="tns:login">
    </wsdl:input>
      <wsdl:output name="loginResponse" message="tns:loginResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LoginSoapBinding" type="tns:Login">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="login">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="login">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="loginResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Login">
    <wsdl:port name="LoginPort" binding="tns:LoginSoapBinding">
      <soap:address location="http://localhost:9090/LoginPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
