
package org.dgac.webservices.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Wed Jul 01 14:42:39 ART 2015
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "login", namespace = "http://server.webservices.dgac.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "login", namespace = "http://server.webservices.dgac.org/", propOrder = {"usrname", "password"})

public class Login {

    @XmlElement(name = "usrname")
    private java.lang.String usrname;
    @XmlElement(name = "password")
    private java.lang.String password;

    public java.lang.String getUsrname() {
        return this.usrname;
    }

    public void setUsrname(java.lang.String newUsrname)  {
        this.usrname = newUsrname;
    }

    public java.lang.String getPassword() {
        return this.password;
    }

    public void setPassword(java.lang.String newPassword)  {
        this.password = newPassword;
    }

}

