
package org.dgac.webservices.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Wed Jul 01 14:42:39 ART 2015
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "loginResponse", namespace = "http://server.webservices.dgac.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loginResponse", namespace = "http://server.webservices.dgac.org/")

public class LoginResponse {

    @XmlElement(name = "return")
    private org.dgac.common.dto.ResultDTO _return;

    public org.dgac.common.dto.ResultDTO getReturn() {
        return this._return;
    }

    public void setReturn(org.dgac.common.dto.ResultDTO new_return)  {
        this._return = new_return;
    }

}

